import {Engine,Mesh,BoxGeometry,BasicMaterial,SimplePhysics,PostProcess,Texture2D,Vector3} from '../src';
import './showcase.css';

const root=document.querySelector<HTMLDivElement>('#showcase')!;
root.innerHTML=`<header class="top"><div class="brand"><b>◈</b> mini / lab</div><div class="sub">engine extensions / live examples</div><a href="https://github.com/razorbladee/mini-3d-engine" target="_blank">GitHub ↗</a></header><main><section class="intro"><p class="eyebrow">MINI 3D ENGINE / 0.1</p><h1>Small experiments,<br><em>real engine APIs.</em></h1><p class="lede">Three focused demos show what the extension layer can already do: load an image, integrate motion, and chain a post-process pass.</p></section><nav class="tabs"><button class="tab active" data-tab="texture">01 / Texture2D</button><button class="tab" data-tab="physics">02 / SimplePhysics</button><button class="tab" data-tab="post">03 / PostProcess</button></nav><section class="demo-grid"><article class="demo active" id="texture"><div class="demo-copy"><span class="number">01</span><h2>Texture loading</h2><p>Loads a browser image through <code>Texture2D.load()</code>, decodes it asynchronously, and presents the result without blocking the scene.</p><button class="run" id="load-texture">Load texture <span>↗</span></button><p class="result" id="texture-result">Ready to load</p></div><div class="visual texture-visual"><canvas id="texture-canvas"></canvas><span class="visual-label">checker / generated at runtime</span></div></article><article class="demo" id="physics"><div class="demo-copy"><span class="number">02</span><h2>Gravity + floor</h2><p>A real <code>SimplePhysics</code> body falls under gravity and settles at <code>y = 0</code>. No fake animation loop here.</p><button class="run" id="reset-physics">Drop again <span>↻</span></button><p class="result" id="physics-result">velocity: 0.00</p></div><div class="visual physics-visual"><canvas id="physics-canvas"></canvas><span class="visual-label">y = 0 / floor constraint</span></div></article><article class="demo" id="post"><div class="demo-copy"><span class="number">03</span><h2>Post-processing</h2><p>Builds a pass chain with <code>PostProcess.add()</code>. Toggle the treatment to compare the raw buffer and graded output.</p><button class="run" id="toggle-post">Enable grade <span>◐</span></button><p class="result" id="post-result">1 pass registered</p></div><div class="visual post-visual"><div class="post-scene"><i></i><b></b><em></em></div><span class="visual-label">color grade / vignette preview</span></div></article></section></main>`;

const tabs=[...document.querySelectorAll<HTMLButtonElement>('.tab')];const demos=[...document.querySelectorAll<HTMLElement>('.demo')];tabs.forEach(tab=>tab.onclick=()=>{tabs.forEach(t=>t.classList.toggle('active',t===tab));demos.forEach(d=>d.classList.toggle('active',d.id===tab.dataset.tab))});
function checker(canvas:HTMLCanvasElement){const ctx=canvas.getContext('2d')!;const size=canvas.width=canvas.height=360;for(let y=0;y<8;y++)for(let x=0;x<8;x++){ctx.fillStyle=(x+y)%2?'#8068dc':'#eeeafd';ctx.fillRect(x*size/8,y*size/8,size/8,size/8)}ctx.fillStyle='#292938';ctx.font='600 22px Space Grotesk';ctx.fillText('Texture2D',24,330)}
const textureCanvas=document.querySelector<HTMLCanvasElement>('#texture-canvas')!;checker(textureCanvas);document.querySelector('#load-texture')!.addEventListener('click',async()=>{const result=document.querySelector('#texture-result')!;result.textContent='Decoding image…';const imageCanvas=document.createElement('canvas');imageCanvas.width=imageCanvas.height=2;const imageCtx=imageCanvas.getContext('2d')!;imageCtx.fillStyle='#8068dc';imageCtx.fillRect(0,0,2,2);const texture=await Texture2D.load(imageCanvas.toDataURL());result.textContent=`Loaded ${texture.image.width}×${texture.image.height} texture`});
const physicsCanvas=document.querySelector<HTMLCanvasElement>('#physics-canvas')!;const physicsCtx=physicsCanvas.getContext('2d')!;const physics=new SimplePhysics();const body=new Mesh(new BoxGeometry(.6),new BasicMaterial({color:'#df9c62'}));body.position.y=1;physics.addBody(body,new Vector3(0,0,0));function drawPhysics(){physicsCanvas.width=Math.max(1,physicsCanvas.clientWidth*2);physicsCanvas.height=Math.max(1,physicsCanvas.clientHeight*2);physicsCtx.setTransform(2,0,0,2,0,0);physicsCtx.clearRect(0,0,physicsCanvas.clientWidth,physicsCanvas.clientHeight);physicsCtx.fillStyle='#dedee7';physicsCtx.fillRect(0,physicsCanvas.clientHeight-28,physicsCanvas.clientWidth,1);const y=physicsCanvas.clientHeight-42-body.position.y*30;physicsCtx.fillStyle='#df9c62';physicsCtx.fillRect(physicsCanvas.clientWidth/2-24,y,48,48);document.querySelector('#physics-result')!.textContent=`height: ${body.position.y.toFixed(2)} / velocity integrated`;physics.step(1/60);requestAnimationFrame(drawPhysics)}document.querySelector('#reset-physics')!.onclick=()=>{body.position.y=3;physics.addBody(body,new Vector3())};drawPhysics();
const post=new PostProcess().add({apply(){}});let graded=false;document.querySelector('#toggle-post')!.onclick=()=>{graded=!graded;document.querySelector('.post-visual')!.classList.toggle('graded',graded);document.querySelector('#toggle-post')!.innerHTML=graded?'Disable grade <span>◐</span>':'Enable grade <span>◐</span>';document.querySelector('#post-result')!.textContent=graded?'Grade active / 1 pass':'1 pass registered'});
void Engine;void Mesh;void BasicMaterial;
