import { Node } from '../core/Node'; import { Mesh } from '../objects/Mesh'; import { BufferGeometry } from '../geometry/BufferGeometry'; import { StandardMaterial } from '../materials/StandardMaterial';
export type LoadedModel={scene:Node;animations:unknown[]};
export class GLTFLoader {
 async load(url:string):Promise<LoadedModel>{const r=await fetch(url);if(!r.ok)throw new Error(`Unable to load glTF: ${r.status} ${r.statusText}`);const base=new URL('.',url);return url.toLowerCase().endsWith('.glb')?this.parseGlb(await r.arrayBuffer(),base):this.parseJson(await r.json(),base)}
 async parseGlb(data:ArrayBuffer,base=new URL('.',globalThis.location?.href??'http://localhost/')):Promise<LoadedModel>{const v=new DataView(data);if(data.byteLength<20||v.getUint32(0,true)!==0x46546c67)throw new Error('Invalid GLB header');const jsonLength=v.getUint32(12,true),jsonType=v.getUint32(16,true);if(jsonType!==0x4e4f534a)throw new Error('GLB JSON chunk is missing');const jsonText=new TextDecoder().decode(new Uint8Array(data,20,jsonLength)).replace(/\0+$/,'').trim();const json=JSON.parse(jsonText);const binHeader=20+jsonLength;const binLength=binHeader+8<=data.byteLength?v.getUint32(binHeader,true):0;const binType=binHeader+8<=data.byteLength?v.getUint32(binHeader+4,true):0;const buffers=binType===0x004e4942?[data.slice(binHeader+8,binHeader+8+binLength)]:[];return this.build(json,buffers,base)}
 async parseJson(json:any,base:URL):Promise<LoadedModel>{const buffers=await Promise.all((json.buffers??[]).map(async(b:any)=>{if(b.uri?.startsWith('data:'))return this.decodeDataUri(b.uri);const r=await fetch(new URL(b.uri,base));if(!r.ok)throw new Error(`Unable to load glTF buffer: ${r.status}`);return r.arrayBuffer()}));return this.build(json,buffers,base)}
 private decodeDataUri(uri:string){const raw=atob(uri.split(',')[1]);const bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);return bytes.buffer}
 private build(json:any,buffers:ArrayBuffer[],_base:URL):LoadedModel{const root=new Node();const read=(index:number)=>{const a=json.accessors[index],b=json.bufferViews[a.bufferView],buffer=buffers[b.buffer];if(!a||!b||!buffer)throw new Error(`Invalid glTF accessor ${index}`);const C=a.componentType===5126?Float32Array:a.componentType===5125?Uint32Array:a.componentType===5123?Uint16Array:Uint8Array;const n=a.type==='VEC4'?4:a.type==='VEC3'?3:a.type==='VEC2'?2:1;const offset=(b.byteOffset??0)+(a.byteOffset??0);return {values:new C(buffer,offset,a.count*n),count:a.count,n};};const meshes=(json.meshes??[]).map((m:any)=>{const p=m.primitives?.[0];if(!p?.attributes?.POSITION)return null;const pos=read(p.attributes.POSITION);let positions=Array.from(pos.values) as number[];const normals=p.attributes.NORMAL?Array.from(read(p.attributes.NORMAL).values) as number[]:undefined;const uvs=p.attributes.TEXCOORD_0?Array.from(read(p.attributes.TEXCOORD_0).values) as number[]:undefined;if(p.indices!==undefined){const idx=Array.from(read(p.indices).values) as number[];const expand=(src:number[]|undefined,step:number)=>src?idx.flatMap(i=>src.slice(i*step,i*step+step)):undefined;positions=expand(positions,3)!;const expandedNormals=expand(normals??[],3);const expandedUvs=expand(uvs??[],2);const pbr=json.materials?.[p.material]?.pbrMetallicRoughness;return new Mesh(new BufferGeometry(positions,expandedNormals,expandedUvs),new StandardMaterial({color:'#b5b1c6',roughness:pbr?.roughnessFactor??.5,metalness:pbr?.metallicFactor??0}))}const pbr=json.materials?.[p.material]?.pbrMetallicRoughness;return new Mesh(new BufferGeometry(positions,normals,uvs),new StandardMaterial({color:'#b5b1c6',roughness:pbr?.roughnessFactor??.5,metalness:pbr?.metallicFactor??0}))});const scene=json.scenes?.[json.scene??0];for(const ni of scene?.nodes??[]){const n=json.nodes?.[ni],mesh=meshes[n?.mesh];if(mesh){if(n.translation)mesh.position.set(...n.translation);if(n.scale)mesh.scale.set(...n.scale);root.add(mesh)}}return{scene:root,animations:json.animations??[]};}
}
